Revert "explicitly state the Dependencies of the packages"
This reverts commit b94610ac56425ceea7b764c9a825f2a48a9432b2.

> Error: The project spec 'Khipus' in project BaselineOfKhipus has incompatible
> specs. MetacelloPackageSpec and MetacelloProjectReferenceSpec are not
> compatible.